# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache:
  packages: true
  directories:
  - .htmlproofer-book-cache
  - .htmlproofer-readme-cache

# Install html-proofer
before_install:
  - gem install html-proofer
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # Speed up the html-proofer install

script:
- Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
- htmlproofer --storage-dir .htmlproofer-book-cache --timeframe 28d _book
- Rscript -e "rmarkdown::render('README.md', 'github_document', output_file = 'program-readme.md', output_dir = '_book')"
- cp -r materials _book
- tools/_proof.sh --storage-dir .htmlproofer-readme-cache _book/program-readme.html
- rm _book/program-readme.md

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT  # Set in the settings page of your repository, as a secure variable
  local_dir: _book
  on:
    branch: master
